version: '3.8'

services:
    webapp:
        container_name: edt.webapp
        build: .
        ports:
            - "5000:80"
            - "5001:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
        networks:
            - web
            - db

    mongodb:
        container_name: edt.mongodb
        image: mongo
        restart: on-failure
        ports:
          - 27017:27017
        environment:
           - MONGO_INITDB_ROOT_USERNAME=admin
           - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
           - mongo-data:/data/db
        networks:
            db:
                aliases:
                    - mongodb

    mongo-express:
        container_name: edt.mongo-express
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
        networks:
            - web
            - db

volumes:
  mongo-data:
    driver: local

networks:
    db:
    web:
        name: frontend
        driver: bridge